# Generated by Django 5.0 on 2024-06-16 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu_docs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_type', models.CharField(choices=[('1', 'Реферат'), ('2', 'Самостоятельная работа студента'), ('3', 'Курсовая работа'), ('4', 'Доклад')], max_length=255)),
                ('language_of_work', models.CharField(choices=[('1', 'Кыргызча'), ('2', 'Русский'), ('3', 'English')], max_length=255)),
                ('work_theme', models.CharField(max_length=255)),
                ('discipline', models.CharField(max_length=255)),
                ('page_count', models.CharField(choices=[('1', '1-10'), ('2', '10-20'), ('3', '20-30'), ('4', '30-40')], max_length=255)),
                ('wishes', models.CharField(max_length=255)),
                ('cover_page_data', models.CharField(choices=[('1', 'Да'), ('2', 'Нет'), ('3', 'Пустой титульный лист')], max_length=255)),
                ('university', models.CharField(blank=True, max_length=255)),
                ('author_name', models.CharField(blank=True, max_length=255)),
                ('group_name', models.CharField(blank=True, max_length=255)),
                ('teacher_name', models.CharField(blank=True, max_length=255)),
                ('subtopics', models.JSONField()),
                ('context', models.JSONField()),
                ('status', models.BooleanField(default=False)),
                ('file', models.FileField(upload_to='documents/')),
            ],
        ),
        migrations.DeleteModel(
            name='Plan',
        ),
    ]
