# Generated by Django 5.0 on 2024-07-03 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu_docs', '0002_alter_word_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='author_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='group_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='teacher_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='university',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
