# Generated by Django 5.0 on 2024-07-05 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu_docs', '0003_alter_word_author_name_alter_word_group_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='discipline',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
