# Generated by Django 5.0 on 2024-07-05 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu_docs', '0004_alter_word_discipline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='discipline',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='word',
            name='wishes',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
