version: '3.9'

services:
  application:
    build:
      context: app
    env_file:
      - .env
    container_name: app
    restart: unless-stopped
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./app:/app/application
    ports:
      - '8000:8000'
    depends_on:
      - database

#  bot:
#    build:
#      context: app
#    container_name: tg_bot
#    command: python run_polling.py
#    volumes:
#      - ./app:/app/application
#    env_file:
#      - .env
#    depends_on:
#      - application

  database:
    image: postgres:16.2-alpine3.18
    env_file: .env
    restart: unless-stopped
    ports:
      - '5555:5432'
    volumes:
      - database-storage:/var/lib/postgresql/data

volumes:
  database-storage:
