version: '3'

services:
  application:
    build:
      context: server
      dockerfile: Dockerfile.prod
    env_file:
      - .env.prod
    container_name: makala_box
    restart: unless-stopped
    command: gunicorn --reload server.wsgi -b 0.0.0.0:8000 --timeout 5
    expose:
      - 8000
    volumes:
      - ./server:/app/application
      - static_volume:/app/application/static
      - media_volume:/app/application/media
    depends_on:
      - database

  database:
    image: postgres:16.2-alpine3.18
    env_file: .env.prod
    restart: unless-stopped
    volumes:
      - database-storage:/var/lib/postgresql/data

  nginx:
    build: ./nginx
    ports:
      - '80:80'
      - '443:443'
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    volumes:
      - static_volume:/app/application/static
      - media_volume:/app/application/media
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - application

  certbot:
    image: certbot/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 24h & wait $${!}; done;'"
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot

volumes:
  database-storage:
  static_volume:
  media_volume:
