# Generated by Django 5.0 on 2024-06-21 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='tg_user_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
