# Generated by Django 5.0 on 2024-06-21 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_payment_tg_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='receipt_image_id',
            field=models.TextField(),
        ),
    ]
