# Generated by Django 5.0 on 2024-07-03 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_alter_payment_status'),
        ('edu_docs', '0003_alter_word_author_name_alter_word_group_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='word',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='edu_docs.word'),
        ),
    ]
