# Generated by Django 5.0 on 2024-06-21 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_payment_created_payment_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='tg_user_id',
            field=models.BigIntegerField(),
        ),
    ]
