# Generated by Django 5.0 on 2024-07-10 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_payment_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='price',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
