# Generated by Django 5.0 on 2024-06-21 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_alter_payment_tg_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='tg_username',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
