# Generated by Django 5.0 on 2024-06-21 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_alter_payment_tg_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='tg_username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
